services:
  db:
    image: mariadb:10.11
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - ./db.env

  app:
    image: matomo:fpm-alpine
    restart: always
    links:
      - db
    volumes:
      # - ./config:/var/www/html/config:z
      # - ./logs:/var/www/html/logs:z
      - matomo:/var/www/html:z
    environment:
      - MATOMO_DATABASE_HOST=db
      - PHP_MEMORY_LIMIT=2048M
    env_file:
      - ./db.env

  web:
    image: nginx:alpine
    restart: always
    networks:
      - default
      - external
    volumes:
      - matomo:/var/www/html:z,ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:z,ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=external"
      - "traefik.http.routers.${TRAEFIK_NAME:?}.rule=Host(`${TRAEFIK_HOST:?}`) || Host(`www.${TRAEFIK_HOST:?}`)"
      - "traefik.http.routers.${TRAEFIK_NAME:?}.middlewares=${TRAEFIK_MIDDLEWARES:-}"
      - "traefik.http.routers.${TRAEFIK_NAME:?}.entrypoints=https"
      - "traefik.http.routers.${TRAEFIK_NAME:?}.tls=true"
      - "traefik.http.routers.${TRAEFIK_NAME:?}.tls.certresolver=baboon"
      - "traefik.port=80"

volumes:
  db:
  matomo:

networks:
  external:
    external: true