services:
  db:
    image: mariadb:10.11
    command: --max-allowed-packet=64MB
    restart: always
    networks:
      - default
    volumes:
      - db:/var/lib/mysql:Z
      - /etc/localtime:/etc/localtime:ro
    environment:
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_INITDB_SKIP_TZINFO: 1
      MARIADB_DISABLE_UPGRADE_BACKUP: 1
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
      MYSQL_DATABASE: ${DB_NAME:-matomo}
      MYSQL_USER: ${DB_USER:-matomo}
      MYSQL_PASSWORD: ${DB_PASSWORD:-matomo}

  app:
    image: matomo:fpm-alpine
    restart: always
    networks:
      - default
    links:
      - db
    volumes:
      # - ./config:/var/www/html/config:z
      # - ./logs:/var/www/html/logs:z
      - /etc/localtime:/etc/localtime:ro
      - matomo:/var/www/html:z
    environment:
      PHP_MEMORY_LIMIT: 2048M
      MATOMO_DATABASE_HOST: db
      MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_TABLES_PREFIX: matomo_
      MATOMO_DATABASE_USERNAME: ${DB_USER:-matomo}
      MATOMO_DATABASE_PASSWORD: ${DB_PASSWORD:-matomo}
      MATOMO_DATABASE_DBNAME: ${DB_NAME:-matomo}

  web:
    image: nginx:alpine
    restart: always
    networks:
      - default
      - external
    volumes:
      - matomo:/var/www/html:z,ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:z,ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=external"
      - "traefik.http.routers.${TRAEFIK_NAME:?}.rule=Host(`${TRAEFIK_HOST:?}`) || Host(`www.${TRAEFIK_HOST:?}`)"
      - "traefik.http.routers.${TRAEFIK_NAME:?}.middlewares=${TRAEFIK_MIDDLEWARES:-}"
      - "traefik.http.routers.${TRAEFIK_NAME:?}.entrypoints=https"
      - "traefik.http.routers.${TRAEFIK_NAME:?}.tls=true"
      - "traefik.http.routers.${TRAEFIK_NAME:?}.tls.certresolver=baboon"
      - "traefik.port=80"

volumes:
  db:
  matomo:

networks:
  external:
    external: true